function r(c) {return Math.floor(Math.random() * c);}

function s(array) {
    return array[r(array.length)];
}

function getevent() {

var adjpos = [
		"anticipatory",
		"emboldened",
		"inspiring",
		"unstoppable",
		"ludicrous",
		"careless",
		"heedless",
		"rational",
		"perceptive",
		"humorous",
		"discerning",
		"enlightened",
		"innocent",
		"expectant",
		"auspicious",
		"uplifting",
		"pious",
		"reassuring",
		"endless",
		"unquenchable",
		"hilarious",
		"passionate",
		"astute",
		"subtle",
		"clever",
		"acute",
		"ingenious",
		"hysterical",
		"kaleidoscopic",
		"glorious",
		"bountiful",
		"joyful",
		"wide-eyed",
		"brilliant",
		"luminous",
		"primeval",
		"timeless",
		"noble",
		"serene",
		"valorous",
		"steadfast",
		"awestruck",
		"interactive",
		"authentic",
		"antique",
		"frivolous",
		"immortal",
		"fluorescent",
		"calibrated",
		"calculated",
		"distant",
		"pelagic",
		"inexorable",
		"hidden",
		"exalted",
		"interconnected",
		"cybernetic",
		"drowsy",
		"distant"
	];

var adjneg = [
		"decrepit",
		"destitute",
		"unsteady",
		"tragic",
		"ruinous",
		"tear-stained",
		"saddened",
		"hopeless",
		"bloodstained",
		"widespread",
		"insidious",
		"churning",
		"writhing",
		"squirming",
		"twisted",
		"maddened",
		"miserable",
		"excruciating",
		"cataclysmic",
		"catastrophic",
		"distraught",
		"gore-spilled",
		"scarred",
		"dubious",
		"insane",
		"negligent",
		"twitching",
		"bubbling",
		"squirming",
		"wriggling",
		"shattered",
		"impossible",
		"vicious",
		"emaciated",
		"rabid",
		"isolated",
		"sadistic",
		"corrupted",
		"diseased",
		"tumorous",
		"venomous",
		"curdled",
		"silent",
		"vacuous",
		"squalid",
		"vulnerable",
		"hazardous",
		"murderous",
		"occult",
		"promiscuous",
		"exhausted",
		"incomprehensible",
		"parasitic",
		"frigid",
		"ashen",
		"labyrinthine",
		"spastic",
		"primitive",
		"catatonic",
		"haunted"
	];

var adjall = [
		"anticipatory",
		"emboldened",
		"inspiring",
		"unstoppable",
		"ludicrous",
		"careless",
		"heedless",
		"rational",
		"perceptive",
		"humorous",
		"discerning",
		"enlightened",
		"innocent",
		"expectant",
		"auspicious",
		"uplifting",
		"pious",
		"reassuring",
		"endless",
		"unquenchable",
		"hilarious",
		"passionate",
		"astute",
		"subtle",
		"clever",
		"acute",
		"ingenious",
		"hysterical",
		"kaleidoscopic",
		"glorious",
		"bountiful",
		"joyful",
		"wide-eyed",
		"brilliant",
		"luminous",
		"primeval",
		"timeless",
		"noble",
		"serene",
		"valorous",
		"steadfast",
		"awestruck",
		"interactive",
		"authentic",
		"antique",
		"frivolous",
		"immortal",
		"fluorescent",
		"calibrated",
		"calculated",
		"distant",
		"pelagic",
		"inexorable",
		"hidden",
		"exalted",
		"interconnected",
		"cybernetic",
		"drowsy",
		"distant",
		"decrepit",
		"destitute",
		"unsteady",
		"tragic",
		"ruinous",
		"tear-stained",
		"saddened",
		"hopeless",
		"bloodstained",
		"widespread",
		"insidious",
		"churning",
		"writhing",
		"squirming",
		"twisted",
		"maddened",
		"miserable",
		"excruciating",
		"cataclysmic",
		"catastrophic",
		"distraught",
		"gore-spilled",
		"scarred",
		"dubious",
		"insane",
		"negligent",
		"twitching",
		"bubbling",
		"squirming",
		"wriggling",
		"shattered",
		"impossible",
		"vicious",
		"emaciated",
		"rabid",
		"isolated",
		"sadistic",
		"corrupted",
		"diseased",
		"tumorous",
		"venomous",
		"curdled",
		"silent",
		"vacuous",
		"squalid",
		"vulnerable",
		"hazardous",
		"murderous",
		"occult",
		"promiscuous",
		"exhausted",
		"incomprehensible",
		"parasitic",
		"frigid",
		"ashen",
		"labyrinthine",
		"spastic",
		"primitive",
		"catatonic",
		"haunted"
    ];

var	nounpos = [
		"reconciliation",
		"rediscovery",
		"rebuilding",
		"alliance",
		"hope",
		"excess",
		"abundance",
		"invention",
		"discovery",
		"advancement",
		"revelation",
		"progress",
		"perplexity",
		"confusion",
		"faith",
		"veneration",
		"inner strength",
		"recovery",
		"honor",
		"duty",
		"calculation",
		"enlightenment",
		"awakening",
		"peace",
		"justice",
		"kindness",
		"empathy",
		"equality",
		"liberty",
		"faith",
		"awakening",
		"slumber",
		"commerce",
		"truth",
		"clarity",
		"inspiration",
		"affection",
		"celebration",
		"contemplation",
		"artistry",
		"cleansing",
		"judgment",
		"courage",
		"liberation",
		"tenderness",
		"protest",
		"serenity",
		"recovery",
		"rebirth",
		"rejuvenation",
		"restoration",
		"insight",
		"eminence",
		"honesty"
	];

var	nounneg = [
		"savagery",
		"ignorance",
		"slavery",
		"degradation",
		"abasement",
		"extermination",
		"violence",
		"bloodlust",
		"carnage",
		"fury",
		"villainy",
		"temptation",
		"disorientation",
		"heresy",
		"bottomlessness",
		"hunger",
		"ruin",
		"dishonor",
		"despair",
		"sacrifice",
		"defeat",
		"famine",
		"contempt",
		"slaughter",
		"charnel",
		"bloodshed",
		"scorn",
		"corruption",
		"betrayal",
		"scheming",
		"vivisection",
		"vice",
		"plague",
		"famine",
		"nightmare",
		"lasciviousness",
		"treachery",
		"cowardice",
		"terror",
		"butchery",
		"malice",
		"madness",
		"intrusion",
		"tribulation",
		"necrosis",
		"mutation",
		"trauma",
		"avarice"
	];

var	noun = [
        "reconciliation",
		"rediscovery",
		"rebuilding",
		"alliance",
		"hope",
		"excess",
		"abundance",
		"invention",
		"discovery",
		"advancement",
		"revelation",
		"progress",
		"perplexity",
		"confusion",
		"faith",
		"veneration",
		"inner strength",
		"recovery",
		"honor",
		"duty",
		"calculation",
		"enlightenment",
		"awakening",
		"peace",
		"justice",
		"kindness",
		"empathy",
		"equality",
		"liberty",
		"faith",
		"awakening",
		"slumber",
		"commerce",
		"truth",
		"clarity",
		"inspiration",
		"affection",
		"celebration",
		"contemplation",
		"artistry",
		"cleansing",
		"judgment",
		"courage",
		"liberation",
		"tenderness",
		"protest",
		"serenity",
		"recovery",
		"rebirth",
		"rejuvenation",
		"restoration",
		"insight",
		"eminence",
		"honesty",
		"savagery",
		"ignorance",
		"slavery",
		"degradation",
		"abasement",
		"extermination",
		"violence",
		"bloodlust",
		"carnage",
		"fury",
		"villainy",
		"temptation",
		"disorientation",
		"heresy",
		"bottomlessness",
		"hunger",
		"ruin",
		"dishonor",
		"despair",
		"sacrifice",
		"defeat",
		"famine",
		"contempt",
		"slaughter",
		"charnel",
		"bloodshed",
		"scorn",
		"corruption",
		"betrayal",
		"scheming",
		"vivisection",
		"vice",
		"plague",
		"famine",
		"nightmare",
		"lasciviousness",
		"treachery",
		"cowardice",
		"terror",
		"butchery",
		"malice",
		"madness",
		"intrusion",
		"tribulation",
		"necrosis",
		"mutation",
		"trauma",
		"avarice"
	];



var person = [
		"traveler",
		"prospector",
		"penitent",
		"pilgrim",
		"caravaneer",
		"refugee",
		"waif",
		"vagrant",
		"prisoner",
		"raider",
		"marauder",
		"soldier",
		"enforcer",
		"ruler",
		"serf",
		"colonizer",
		"master",
		"researcher",
		"explorer",
		"academic",
		"cultist",
		"hunter",
		"bandit",
		"inquisitor",
		"monk",
		"sage",
		"serf",
		"architect",
		"knight",
		"criminal",
		"rogue",
		"paladin",
		"scout",
		"hussar",
		"barbarian",
		"zealot"
	];

var place =	[
		"orchard",
		"campsite",
		"temple",
		"haven",
		"outlook",
		"wastes",
		"gutter",
		"desolation",
		"crater",
		"redoubt",
		"garrison",
		"citadel",
		"bunker",
		"rampart",
		"palace",
		"bazaar",
		"manse",
		"villa",
		"laboratory",
		"orrery",
		"shrine",
		"spire",
		"altar",
		"pit",
		"chantry",
		"monastery",
		"cavern",
		"dungeon",
		"cathedral",
		"catacomb",
		"mire",
		"garden",
		"mine",
		"desert",
		"gateway",
		"archive",
		"nexus",
		"outpost",
		"forge",
		"parish",
		"isle",
		"archipelago",
		"sea",
		"ocean",
		"peak",
		"bastion",
		"maze",
		"colony",
		"copse",
		"valley",
		"gulch",
		"gaol",
        "summit"
	];

var	leader = [
		"messiah",
		"prophet",
		"shaman",
		"demagogue",
		"slaver",
		"mercenary",
		"gladiator",
		"warlord",
		"tactician",
		"captain",
		"general",
		"champion",
		"herald",
		"agent",
		"count",
		"marquis",
		"oligarch",
		"administrator",
		"professor",
		"dreamer",
		"whisperer",
		"magister",
		"crone",
		"genius"
	];


var name1 = [
		"Eze",
		"Jer",
		"Siri",
		"Ja",
		"Nat",
		"Gor",
		"Grod",
		"An",
		"Leo",
		"Agra",
		"Mem",
		"Heri",
		"Den",
		"Grigo",
		"Vido",
		"Pelli",
		"Stra",
		"Lumi",
		"Luna",
		"Re",
		"Max",
		"Vash",
		"Xor"
	];

var name2 = [
		"kiel",
		"emia",
		"ko",
		"thew",
		"lise",
		"gar",
		"mar",
		"dak",
		"drif",
		"dron",
		"tus",
		"medes",
		"non",
		"ates",
		"hov",
		"sch",
		"grin",
		"vic",
		"rov",
		"mar",
		"jec"
	];

var name3 = [
		"a",
		"o",
		"i"
	];

var name4 = [
		"Yl'",
		"Id",
		"Bin",
		"O'",
		"Ir",
		"Ul",
		"Yn",
		"An"
	];

var name5 = [
		"Xi",
		"Od",
		"Sha",
		"Tiri",
		"Ka",
		"Ar",
		"Bel",
		"Rel",
		"Bur",
		"Al"
	];

var name6 = [
		"mar",
		"rin",
		"ber",
		"arth",
		"gath",
		"sus",
		"ro",
		"zul",
		"kul",
		"ko"
	];

var name = [
		s(name1)+s(name2)+s(name3),
		s(name1)+s(name2)+s(name3)+" "+s(name4)+" "+s(name5)+s(name6)+s(name3),
        s(name1)+s(name2)+s(name3)+" "+s(name5)+s(name6)+s(name3),
		s(name1)+s(name2),
		s(name1)+s(name2)+" "+s(name4)+" "+s(name5)+s(name6),
		s(name1)+s(name2)+s(name3)+" "+s(name4)+" "+s(name5)+s(name6),
        s(name1)+s(name2)+" "+s(name4)+" "+s(name5)+s(name6)+s(name3),
        s(name1)+s(name2)+" "+s(name5)+s(name6)+s(name3),
        s(name1)+s(name2)+s(name3)+" "+s(name5)+s(name6),
        s(name1)+s(name2)+s(name3)+" "+s(name5)+s(name6)+s(name3),
    ];

var verbpos = [
        "discover",
        "protect",
        "uplift",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
];        

var verbneg = [        
        "betray",
        "murder",
        "slaughter",
        "ruin",
        "corrupt",
        "dishonor",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
];

var verb = [
    verbpos,
    verbneg
];

var authority = [
		"council",
		"spirits",
		"elders",
		"ruling-class",
		"committee",
		"oligarchy",
		"clergy"
	];

var time = [
		"hours",
		"weeks",
		"months",
		"years",
		"centuries"
	];

var rebelverb = [
		"question",
		"disobey",
		"revolt against",
		"debate",
		"dismantle"
	];

var reason = [
		"in order to build a lasting peace",
		"to bring "+s(nounpos)+" to the downtrodden",
		"against the wishes of the "+s(authority)+"",
		"in order to prepare for dark days ahead",
		"establishing peace between factions",
		"in order to send a message",
		"in order to eke out a living of scarcity",
		"in order to fill starving bellies",
		"clinging to a fragile hope",
		"in order to eke out a meager existence",
		"in order to snuff out all life",
		"seeking "+s(nounpos)+" at any cost",
		"in order to rout the foes in the field",
		"in order to slaughter their foes",
		"in order to destroy the enemy way of life",
		"betraying long time allies",
		"in order to subjugate the weak",
		"in order to dominate the political system",
		"squandering the discoveries of ages past for personal gain",
		"in order to maximize profit",
		"in order to satisfy sheer curiosity",
		"for the betterment of all",
		"chasing the next big discovery",
		"in order to solve the great intellectual puzzle of the age",
		"in order to reverse engineer the madness that came before",
		"due to the hidden machinations of long-lost gods",
		"in order to discover the secrets locked within the human form",
		"in order to venerate the whispering voices",
		"possessed by twisted ambition",
		"advancing alien designs",
		"spurred on by curdled thoughts",
		"in the name of "+s(noun)+"",
		"ushering in a "+s(time)+"-long age of "+s(noun)+"",
		"igniting a cycle that would last "+s(time)+"",
		"haunted by the dreams of dead gods",
		"to unleash "+s(nounneg)+" unto the masses",
		"in order to fulfill a mystic vision"
	];

var	createverb = [
		"created",
		"founded",
		"discovered",
		"built",
		"rebuilt",
		"engineered",
		"constructed"
	];

var	waroutcome = [
		"destroying them utterly",
		"displacing them",
		"killing all but a single person: "+s(name)+" the "+s(leader)+"",
		"capturing them",
		"enslaving them",
		"accepting their surrender",
		"sacrificing them"
	];   

var warverb = [
		"ransacked",
		"burned down",
		"besieged",
		"destroyed",
		"demolished"
	];

var	result = [
		"This would stave off their eventual demise... for a time.",
		"Sadly, their struggles would all be for naught.",
		"They went on to transcend the mortal realm.",
		"They went on to enter a new age of prosperity.",
		"This would lead to the eventual ruination of all parties involved.",
		"This would end centuries of bitter conflict.",
		"This would embroil the world in centuries of war.",
		"This would save them from "+s(adjneg)+" "+s(nounneg)+".",
		"The reaper would claim them all in the end.",
		"All this would be lost in the maelstrom of chaos that would follow."
	];

var revengeverb = [
		"seeks vengeance",
		"seeks reparations",
		"wishes to free their people",
		"wishes to see the aggressors brought to justice",
		"is prepared to strike back",
		"was too late to save their people",
		"plots and schemes to bring the aggressors' downfall "
	];

var stratagem = [
		"all-out assault",
		"subtle trickery",
		"ingenious strategy",
		"shocking brutality",
		"sheer intimidation",
		"brilliant skill-at-arms",
		"inspiring leadership",
		"attrition",
		"shock-and-awe"
	];

var assassinverb = [
		"guillotined",
		"butchered",
		"poisoned",
		"staged a coup d'etat against",
		"murdered",
		"beheaded"
	];
var assassinnoun = [
		"killers",
		"assassins",
		"agents",
		"mercenaries",
		"executioners"
	];
var politics = [
		"through masterful manipulation of the political system",
		"through egregious voter fraud",
		"through "+s(adjneg)+" skullduggery",
		"through selling their soul to a "+s(adjall)+" higher power",
		"by enacting "+s(adjall)+" plans centuries in the making",
		"through scapegoating the "+s(person)+"s for all the nation's woes"
	];

var ancientsecret = [
		s(adjall)+" rituals",
		s(adjall)+" technology",
		s(adjall)+" artifacts",
		s(adjall)+" secrets",
		"the secrets of "+s(noun),
		"the hidden worship of "+s(noun),
	];

var treatyverb = [
		"signed a document",
		"shook hands",
		"engaged in ritual scarring",
		"exchanged "+s(person)+"s as hostages",
		"killed themselves"
	];

var deed = [
		"defeat the "+s(leader)+" "+s(name)+", becoming "+s(leader)+" in their stead",
		"usher in a +"+s(adjall)+" age of "+s(noun),
		"begin a "+s(adjneg)+" war with the "+s(person)+"s of the "+s(adjall)+" "+s(place)+" that would last "+s(time),
		"slaughter the "+s(adjall)+" "+s(person)+"s of "+s(noun),
		"save the "+s(adjall)+" "+s(person)+"s of "+s(noun)
	];

var entity = [
		"dark spirit",
		"relic AI",
		"rogue god",
		"cosmic entity",
		"immortal overlord"
	];

var defeatverb = [
		"banished",
		"defeated",
		"consumed",
		"tricked",
		"slain"
	];

var changeevent = [
		"war",
		"plague",
		"famine",
		"hardship",
		"conflict",
		"ignorance"
	];



var ancientsecret = [
		s(adjall)+" rituals",
		s(adjall)+" technology",
		s(adjall)+" artifacts",
		s(adjall)+" secrets",
		"the secrets of "+s(noun),
		"the hidden worship of "+s(noun),
	];

var treatyverb = [
		"signed a document",
		"shook hands",
		"engaged in ritual scarring",
		"exchanged "+s(person)+"s as hostages",
		"killed themselves"
	];

var deed = [
		"defeat the "+s(leader)+" "+s(name)+", becoming "+s(leader)+" in their stead",
		"usher in a "+s(adjall)+" age of "+s(noun),
		"begin a "+s(adjneg)+" war with the "+s(person)+"s of the "+s(adjall)+" "+s(place)+" that would last "+s(time),
		"slaughter the "+s(adjall)+" "+s(person)+"s of "+s(noun),
		"save the "+s(adjall)+" "+s(person)+"s of "+s(noun)
	];

var eventstructure = [
        "After "+s(time)+" of "+s(adjneg)+" "+s(changeevent)+", the "+s(person)+"s of the "+s(adjall)+" "+s(place)+" began to "+s(rebelverb)+" the "+s(noun)+" of "+s(leader)+" "+s(name)+", "+s(reason)+". "+s(result)+"",
		"In order to bring "+s(adjpos)+" "+s(nounpos)+" to the "+s(adjall)+" "+s(person)+"s,  "+s(leader)+" "+s(name)+" led the reconstruction of the "+s(adjall)+" "+s(place)+", "+s(reason)+". "+s(result)+"",
		"The "+s(leader)+" "+s(name)+" "+s(createverb)+" the "+s(place)+" of "+s(noun)+" for the glory of their fellow "+s(person)+"s. It would be a place of "+s(adjpos)+" "+s(nounpos)+", until its collapse due to "+s(adjneg)+" "+s(nounneg)+".",
		"After "+s(time)+" of "+s(adjneg)+" war, the "+s(adjall)+" "+s(person)+"s of "+s(noun)+" made peace with the "+s(person)+"s of the "+s(adjall)+" "+s(place)+". "+s(name)+" the "+s(adjall)+" "+s(leader)+" and "+s(name)+" the "+s(adjall)+" "+s(leader)+" "+s(treatyverb)+" to solidify the "+s(adjpos)+" agreement.",
		"The "+s(person)+"s of the "+s(adjall)+" "+s(place)+" vanished completely from history. One survivor, "+s(name)+" the "+s(leader)+", remained in an "+s(adjneg)+" state, telling "+s(adjneg)+" tales of "+s(nounneg)+" and "+s(nounneg)+" to all "+s(person)+"s who would listen.",
		""+s(name)+", "+s(leader)+" of the "+s(adjall)+" "+s(place)+", forsook the taboos of their fellow "+s(person)+"s, learning the "+s(adjall)+" arts of "+s(noun)+", "+s(reason)+". "+s(result)+"",
		"The "+s(person)+"s of the "+s(adjall)+" "+s(place)+" fell to ruin, forgetting their "+s(adjpos)+" history and succumbing to "+s(adjneg)+" "+s(nounneg)+". Now only the "+s(leader)+" "+s(name)+" remains to tell tales of their "+s(adjall)+" culture.",
		"The "+s(adjall)+" "+s(person)+"s of "+s(noun)+" "+s(warverb)+" the "+s(place)+" of the "+s(adjall)+" "+s(person)+"s of "+s(noun)+", "+s(waroutcome)+". "+s(name)+" the "+s(leader)+" of "+s(noun)+" led the attack through "+s(stratagem)+". "+s(name)+" the "+s(leader)+" of "+s(noun)+" "+s(revengeverb)+".",
		"After an "+s(adjneg)+" war full of "+s(nounneg)+" that lasted "+s(time)+", the "+s(person)+"s of the "+s(adjall)+" "+s(place)+" surrendered to the "+s(adjall)+" army of the "+s(adjall)+" "+s(person)+"s. "+s(name)+", "+s(leader)+" of the attackers, responded by "+s(waroutcome)+".",
		"The "+s(adjpos)+" army of the "+s(adjpos)+" "+s(person)+"s defeated the "+s(adjneg)+" army of the "+s(adjneg)+" "+s(person)+"s in the "+s(adjall)+" "+s(place)+". "+s(leader)+" "+s(name)+" the "+s(adjpos)+" won the battle through "+s(stratagem)+". "+s(leader)+" "+s(name)+" the "+s(adjneg)+" "+s(revengeverb)+".",
		s(name)+" the "+s(leader)+" betrayed the "+s(person)+"s of the "+s(adjall)+" "+s(place)+", siding with their ancient foes, the "+s(adjall)+" "+s(person)+"s of the "+s(adjall)+" "+s(place)+", "+s(reason)+". "+s(result)+"",
		""+s(assassinnoun)+" from the "+s(adjall)+" "+s(place)+" "+s(assassinverb)+" the ruler "+s(name)+", the "+s(leader)+" of the "+s(place)+" of "+s(noun)+", "+s(reason)+". "+s(result)+"",
		""+s(name)+", "+s(leader)+" of the "+s(adjall)+" "+s(place)+", exploited great masses of "+s(person)+"s "+s(reason)+". "+s(result)+"",
		""+s(name)+" became the "+s(leader)+" of the "+s(adjall)+" "+s(place)+" "+s(politics)+". They went on to enact "+s(adjall)+" laws and build a regime of "+s(noun)+" that would last for "+s(time)+" before falling to "+s(adjneg)+" "+s(nounneg)+".",
		""+s(name)+", of the "+s(adjall)+" "+s(person)+"s of "+s(noun)+", ventured to the "+s(adjneg)+" "+s(place)+" and uncovered the secrets that brought the "+s(adjneg)+" downfall of the "+s(adjall)+" "+s(person)+"s of "+s(noun)+". "+s(result)+"",
		"In a fit of "+s(adjall)+" "+s(noun)+", "+s(name)+" of the "+s(adjall)+" "+s(person)+"s ventured to the "+s(adjall)+" "+s(place)+" and discovered the secrets of "+s(noun)+" and "+s(noun)+". They would use this "+s(adjall)+" knowledge to "+s(deed)+".",
		"Upon discovering their "+s(noun)+", "+s(name)+" of the "+s(adjall)+" "+s(person)+"s ventured to the "+s(adjall)+" "+s(place)+" to learn the "+s(adjall)+" secrets of "+s(noun)+", which they would later use to "+s(deed)+".",
		"After "+s(time)+" of imprisonment, the "+s(adjneg)+" "+s(entity)+" "+s(name)+" escaped their "+s(adjall)+" bonds, becoming worshipped as a "+s(adjall)+" god of "+s(noun)+" and "+s(noun)+" by the "+s(person)+"s of the "+s(adjall)+" "+s(place)+".",
		""+s(name)+", "+s(leader)+" of the "+s(adjall)+" "+s(person)+"s and "+s(name)+", "+s(leader)+" of the "+s(adjall)+" "+s(person)+"s were married at the "+s(adjall)+" "+s(place)+" in the name of "+s(noun)+" and "+s(noun)+", "+s(reason)+".",
		""+s(name)+" the "+s(leader)+" was exiled by the "+s(adjall)+" "+s(person)+"s from the "+s(adjall)+" "+s(place)+" for the crimes of "+s(adjneg)+" "+s(nounneg)+" and "+s(adjneg)+" "+s(nounneg)+". "+s(result)+""
	];    

document.getElementById("devent").innerHTML=s(eventstructure);

}