var starvelist333 = ["Stage One: Hungry. Party must spend 300sp on food/person OR eat an edible opponent, PC, or henchman every three days. Return all levels drained from subsequent stages of hunger.", "Stage Two: Starving. Party must either spend 600sp on food/person or eat an edible opponent, PC, or henchman to return to Stage One. Every time the opportunity to do this comes up, but they DO NOT do it, they suffer one level drain.", "Stage Three: Dying. PCs must spend 1000sp on food per party member OR consume an edible opponent, PC, or henchman to return to Stage One. Every member of the party loses one level for every 24 hours they spend in this stage. If they hit zero, they die."];
var i = 0;
document.getElementById('starvation333').innerHTML = starvelist333[i];

forward1333 = function(){
    if(i == starvelist333.length-1){
        i = 0;
    } else {
        i++;
    }
document.getElementById("starvation333").innerHTML = starvelist333[i];
}

backward1333 = function(){
    if(i == 0){
        i = starvelist333.length-1;
    } else {
        i--;
    }
document.getElementById("starvation333").innerHTML = starvelist333[i];
}


var hypolist333 = ["Stage 1: Cannot feel hands and feet. Movement is halved, cannot do fine work with hands.", "Stage 2: Cannot feel arms or legs. If they fall they cannot stand up and must crawl. Can no longer swim.", "Stage 3: Only wants sleep. Another PC must accompany them for every stated action. If not, sufferer lies down and goes to sleep. Loses 1hp per minute until death."];
var i = 0;
document.getElementById('hypothermia333').innerHTML = hypolist333[i];

forward2333 = function(){
    if(i == hypolist333.length-1){
        i = 0;
    } else {
        i++;
    }
document.getElementById("hypothermia333").innerHTML = hypolist333[i];
}

backward2333 = function(){
    if(i == 0){
        i = hypolist333.length-1;
    } else {
        i--;
    }
document.getElementById("hypothermia333").innerHTML = hypolist333[i];
}


function r(c){
  return Math.floor(Math.random() * c);
}


function cave333(){


var shape333 = [

`liquid poured from a curved glass`,
`a splayed toad`,
`a wine bottle on its side`,
`a sauce pan with lid and extra handle`,
`a sleeping mouse`,
`a ladies' high-heeled shoe`,
`a strawberry`,
`a theatre-shaped space`,
`an elephant-trunk shaft that bends, narrows, and twists`,
`a sea urchin`,
`a spread-fingered hand held palm-up`,
`a saxophone`,
`a chain of pearls`,
`a cow's udder`,
`an upside-down blowfish with exits at the eyes`,
`a bunny head`,
`a squat, globular ball in a cradle of tubes`,
`an old-style telephone reciever`,
`two cherries on a split stem`,
`a hammerhead shark`,
`big headphones`,
`an eye-dropper`,
`a toucan`,
`a three-legged stool`,
`a bear with exits at the nose and toes`,
`a lip-island on roaring abyssal falls`,
`crossed swords`,
`a lung`,
`a ring with a big diamond on it`,
`a j-curve ski jump slope, with a widowmaker at the peak`,
`a spine`,
`two bells touching`,
`a barbell with a linking tube`,
`a bat with wings spread`,
`a lighting bolt`,
`a pistol`,
`a muffin, with walls that bow out in a rim around the top`,
`an inverted giraffe`,
`two fish hooks meshed`,
`the inside of an inverse pyramid`,
`a rib cage, like the inside of a gigantic corpse`,
`the cheese linking lifted pizza bits`,
`a martini glass`,
`an octopus with narrowing limbs leading off in a star`,
`a U-bend on its side`,
`the inside of a vending machine`,
`a nautilus shell with smashable interior walls`,
`a huge hourglass`,
`tall thin vertical caves linked by crawls at the top and bottom`,
`an ice-cream cone piercing the ice-cream of another beneath`,

];

var stone333 = [

`petal pink marble that almost glows`,
`limestone stained with black clawing growths`,
`limestone stained with bright primary-color chemicals`,
`grim grey granite with quartz crystals like diamond eyes`,
`a densely fossil'd trilobite graveyard`,
`mirror-smooth polished anthracite`,
`storm-shaded slate in flaking cakes`,
`tusk-colored limestone`,
`slick and wet moon-bright calcite`,
`tactile soapstone the color of sick milk`,
`beach-yellow sandstone, easily abraded by touch`,
`black calcite stained by oil and ash`,
`dark-blue granite like a late summer sky`,
`limestone, beautifully banded like infinite cake`,
`haematite veins glinting like stained silver`,
`white-streaked walls with a fossilised guano floor`,
`white, sharp, delicate gypsum flowers`,
`ropes of entangled lava in organic twists`,
`star-bright fool's gold gleaming within dark volcanic stone`,
`limestone in sea-shaded intersecting rills`,
`limestone stained the color of autumnal leaves`,
`coquina, a crumbly-jumbly conglomerate of coral shell`,
`gleaming white calcite boxwork, shining water-slick`,
`paper-white limestone stained by copper like a leaking pen`,
`grey limestone, white calcite cysts like organic growths`,
`streaked with veins disclosing semiprecious gems`,
`obsidian, polished into smooth razors`,
`rainbow banded speleotherms stained by unseen ores`,
`black basalt, ridged and frictive like a vinyl disc`,
`cloud-colored granite with black pyroxene and white quartz`,
`grey lumpen granite with obsidian shards like tears in space`,
`blinding, hand-staining halogen white chalk`,
`red sandstone with fossilised trackmarks`,
`a gnawed out space within a pale gigantic bone,`,
`ore rich stone, black unlightable ferric walls`,
`calm claystone the shade of earthenware`,
`black and glimmering coal`,
`rust with ancient steel beneath`,
`banded serpentinite in tight green/black waves like EEGs`,
`limestone with ghastly yellow sulphur rot`,
`stained flowstone glowing red-black-red like old blood`,
`brown mudstone frozen in swampy wallows`,
`dangerous, unstable, seeping black oil shale`,
`limestone pyritised and filigreed in fool's gold`,
`granite braided with veins of strangely stained ore`,
`limestone the color of a ruined screen`,
`multicolored sandstone formed from sedimented trash glass`,
`soft claystone the color of old books`,
`sea-shaded siltstone in gradual bands`,
`limestone with green olivine like leaves of climbing plants`,

];


var cavefull333 = [

`This cave is shaped like `+shape333[r(50)]+` and is made of `+stone333[r(50)]+`.`

];

document.getElementById("caveplace333").innerHTML = ``+cavefull333[r(1)]+``;

}


function namedcave333(){


var hundredcaves333 = [

`1. Ale-Pour Rappel`,
`2. Ammonitico Russo`,
`3. Antiforest`,
`4. Black Growths Like Melted Crows`,
`5. Bleeding Cadmium Suns`,
`6. Blockage`,
`7. Boulder Hall`,
`8. Carbonised Trees`,
`9. Carved Cave Mega-Tale`,
`10. Cephalopoid Hyper-Fossil`,
`11. Class IV Rapid Dunes`,
`12. Coal Cave`,
`13. Cobalt Kobold Cave`,
`14. Columned Maze`,
`15. Cryobite Bridge`,
`16. Daemon Tusk Cave`,
`17. Death Hope Mural`,
`18. Dog Jaws`,
`19. Dolls' Theatre`,
`20. Elephant Shaft`,
`21. Europium Union`,
`22. Flowstone Cascade`,
`23. Fossil Water Lake`,
`24. Fossilised Hive`,
`25. Fountain of FonteStorbe`,
`26. Friction Climb (Granite)`,
`27. Fulitinous Rainbow`,
`28. Fungal Throttle`,
`29. Ghost Meadow`,
`30. Giant's Pauseway`,
`31. Glazed Cave`,
`32. Grand Elbois`,
`33. Gravitic Twist`,
`34. Grotto of the Fairies`,
`35. Guano Field`,
`36. Gypsum Flower Field`,
`37. Hair Braid Cave`,
`38. Hall of Thirteen`,
`39. Hokusai Wave Cave`,
`40. Hurricane Shaft`,
`41. Ice Fall Traverse`,
`42. Interference Patterns`,
`43. Inverse Lapaiz`,
`44. Leaf Shadow Shards`,
`45. Lens Cave`,
`46. Lock Pick Cave`,
`47. Magnesium Vein Trees`,
`48. Magnetic Spring (Carbonic Acid)`,
`49. Marble Jar`,
`50. Mega-Helictites`,
`51. Metamorphic Tube`,
`52. Neon Cysts`,
`53. Nightmare Falls`,
`54. Not Dark Nor Sombre Wholly`,
`55. Obsidian Bricks`,
`56. Paraplegic Angel of Death`,
`57. Pervotherms`,
`58. Phreatic Maze`,
`59. Pseudolith`,
`60. Pyroxene Riddles`,
`61. Rapturous Sulphate Bleeds`,
`62. Rock Milk Teats`,
`63. Rocklung`,
`64. Sandstone Trackmarks`,
`65. Sarawak Chamber`,
`66. Scrimshaw Madness`,
`67. Ski Jump Boulder Field`,
`68. Skyline Traverse`,
`69. Smelting Furnace`,
`70. Solfatara`,
`71. Speleomen`,
`72. Sperm Whale Graveyard`,
`73. Squeezes`,
`74. Steel Fold Furrow`,
`75. Stone Monkey Cave`,
`76. Suicide Maze`,
`77. Sulphurborn Cave`,
`78. Summerhand Cave`,
`79. Sump Island`,
`80. Sump`,
`81. Sun Temple`,
`82. Super-Oolite Pool`,
`83. Swim Gym`,
`84. Tantalum Vein`,
`85. Tessellated Faceprint Floor`,
`86. The Piston`,
`87. Throne of Gold`,
`88. Titanium Etched by the Glance of an Evil Eye`,
`89. Titanribs Corpse Cave`,
`90. TV-Screen-Deep`,
`91. Ulysses Beach`,
`92. Vertical Squeeze (Pizza Cheese)`,
`93. Via Ferrata`,
`94. Vog-Tornado Falls`,
`95. Waitomo Worms`,
`96. Walk in the Park`,
`97. War Grave Cave`,
`98. Whisper Walls`,
`99. Word-Hoard`,
`100. Xenolith Burg`,

];

document.getElementById("namedcaveplace333").innerHTML = ``+hundredcaves333[r(100)]+``;

}


function dark333(){


var kindsofdark333 = [

`Dankscratch: "your light makes you feel more exposed and vulnerable here."`,
`Stippledark: "the shadows here make detail stark, and sharp enough to be almost hostile to the eye."`,
`Parlourdark: "the dark here seems like one you find at home, less alien, threatening. Faces and expressions seem clearer now."`,
`Umbraphillian: "everything seems too deep and far here, but with more awe than fear."`,
`Nefarshade: "you keep having to look twice at things. Nothing seems to be where you thought it was."`,
`Terpsifulgin: "the dark here seems less timeless somehow, the minutes countable."`,
`Aphelionbral: "everything seems imprecise and unclear. Easy to hide or to be hidden from."`,
`Obsidum: "you feel more alone here in the black than ever before."`,
`Houndark: "you feel barely aware of the stone here, over the heat and sound of your breathing and heart."`,
`Scardark: "the dark flickers here, like the edge of campfire, an impish, plotting thing."`,
`Carnacht: "every weakness feels exposed and judged wanting in the weight of the dark here."`,
`Kosomicoscot: "every night is here. Every night feels like it is here with you, bigger than you."`,

];

document.getElementById("darkplace333").innerHTML = ``+kindsofdark333[r(12)]+``;

}


function senses333(){


var smellsounds333 = [

`The smell of a bitter sea and the sound of faint fizzling foretell the presence of an Alkalion.`,
`The smell of the darkest crypt and the sound of cackling foretell the presence of an Anglerlich.`,
`The smell of cold ash and the sound of a dead tongue foretell the presence of the AntiPheonix.`,
`The smell of libraries and rot and the sound tapping sticks of foretell the presence of an Arachnopolis Rex.`,
`The smell of coins on the tongue and the sound of clean flame foretell the presence of Archaeans.`,
`The sound of skull-recieved radio noise foretells the presence of Atomic Bees.`,
`Oppressive silence foretells the presence of a Gigaferret.`,
`The smell of soot, chalk, and oil and the sound of grating and wheezing foretell the presence of a Cancer Bear.`,
`The smell of clean toilets and the sound of 'tk tk tk' foretell the presence of `+String(r(6)+r(6)+r(6)+r(6))+` Cambrimen.`,
`The sound of metal grating on stone foretells the presence of a Castillan Caddis Larva.`,
`The smell of shit, blood, and pus and the sound of moans and gasps foretell the presence of `+String(r(100))+` Cholerids.`,
`The smell of old books, incense, and blood and the sound of rushing wind foretell the coming of Civilopede.`,
`The smell of turned earth and the sound of mud cracking foretell the presence of a Cromagnogolem.`,
`The smell of cold rancid meat and the sound of ultrasonic whirrs foretell the presence of `+String(r(4)+r(4)+r(4)+r(4))+` Egg Dead.`,
`The smell of your own memories reveals the entry to an Eigengrau lair.`,
`The smell of bad medication and the sound of stone on bone foretell the presence of `+String(r(4))+` Fossil Vampires.`,
`The sound of two voices linked foretells the presence of a Fungal Ambassodile.`,
`The smell of mushrooms foretells the presence of `+String(r(20))+` Funginid Slaves and a Leader.`,
`The smell of attics and empty rooms foretells the presence of a Gegenschein.`,
`The sound of rocks in a rotating drum foretells the presence of a Gilgamash.`,
`The smell of a burning plastics factors and the sound of insectiod chattering foretell the presence of an Igneous Wrath.`,
`The smell of sulphur and the sound of primal phonemes foretell the presence of `+String(r(20))+` Ignimbrite Mites.`,
`The smell of faint antiseptic ointment foretells the presence of `+String(r(4)+r(4)+r(4)+r(4))+` Knotsmen.`,
`The smell of oil and guano and the sound of madness reveal the entrance to a Lamenter Roost.`,
`The smell of fresh refrigerated meat and the sound of sharp silence foretells the presence of a Mantis Shrimp`,
`An almost-human smell and the sound of fluting voices foretell the presence of `+String(r(4)+r(4)+r(4)+r(4))+` Meanderthals.`,
`There is a Mondmilch pool.`,
`The ghost of a human scent and the sound of dripping, running water foretell the presence of `+String(r(4)+r(4)+r(4)+r(4))+` Olm.`,
`The smell of oil and iron blood and the sound of wine glass rims foretell the presence of an Oneirocetacean.`,
`The smell of dead bodies and the sound of screaming foretell the presence of a Panic Attack Jack.`,
`Someone takes your hand. It's the Phantom Hand of Gargas!!`,
`The smell of pungent yeast and the sound of throat-choke grunts foretell the presence of `+String(r(6)+r(6)+r(6))+` Psychomycosis Megaspores.`,
`The smell of ash and old blood and the sound of broken animal growls foretell the presence of `+String(r(4)+r(4)+r(4)+r(4))+` Pyroclastic Ghouls.`,
`The smell of faint clean hospitals and the sound of falling glass foretell the presence of a Radiolarian.`,
`The sound of soft, ridiculous plops foretells the presence of `+String(r(20)+r(20)+r(20))+` Scissorfish.`,
`The smell of tin burning and the sound of a furnace screaming foretell the presence of `+String(r(4))+` Silichominids.`,
`The smell of pigs and notable, extreme sounds foretell the presence of `+String(r(8)+r(8)+r(8)+r(8)+r(8))+` Sonic Pigs!`,
`The smell of mortuary spices and the sound of babybones clattering foretell the presence of The Spectre of the Brocken.`,
`The smell of burning stone and the sound of lead bells foretell the presence of `+String(r(50))+` Splinterlads.`,
`The smell of dogs and chlorine and the sound of scrabbling and panting foretell the presence of `+String(r(6)+r(6)+r(6)+r(6))+` Spotlight Dogs.`,
`The sound of distant screaming from above foretells the presence of a Still-Tor-Man.`,
`The smell of greasy static charge and the sound of plinking glass foretell the presence of `+String(r(50))+` Stormsheep.`,
`The smell of yeast and the sound of a harsh animal voice foretell the presence of a Tachyon Troll.`,
`The smell of formaldehyde, ammonia, and blood and the sound of a wet shoe foretell the presence of a Tetracharcarohedron.`,
`The smell of old schoolrooms and the sound of deep thumping foretell the presence of a Titanskull Hermit Crab.`,
`The sound of clacking and rapping foretells the presence of `+String(r(4)+r(4)+r(4)+r(4))+` ToRaptoise.`,
`The smell of a little salt and the sound of faint clattering foretell the presence of a Trilobite Knight.`,
`The smell of sick children foretells the presence of a Trogloraptor.`,
`The smell of musty cupboards and the sound of slight fluttering foretell the presence of `+String(r(50)+r(50)+r(50)+r(50)+r(50))+` Ultraviolet Butterflies.`,
`The smell of dry chalk and the sound of scrapes and grates foretell the presence of `+String(r(4)+r(4))+` Zombie Coral.`,

];

document.getElementById("sensesplace333").innerHTML = ``+smellsounds333[r(50)]+``;

}


function veinsencounter333 (){


var encounter333 = [

`Cancer Bear camouflaged in carved marble.`,
`Crin's Crack, three miles long, one mile deap, four feet wide.`,
`Giant-Saint's tomb, safe retreat for those unarmed.`,
`Silk-train of guarded slaves in single file.`,
`Temple to the Void God, empty when full.`,
`Sombre Substratal anchorite, enraged.`,
`Tombs of the Sphere-Lords, empty now, and smooth.`,
`Umbral-Town, arranged in shadowed segments.`,
`Blind Masons, traipsing and talking of stone.`,
`Olm on a vision quest, what does it see?`,
`Aelf-Adal slavers are waiting for you.`,
`Mermaid Falls, water singing over bone.`,
`Igneous Villa, civilised and black.`,
`The MoonMaster General with his white guard.`,
`Temple to an expunged god, sunk long past.`,
`Husks of boys, abandoned by the child-thief.`,
`Foxfire warrens, threats hide within the lights.`,
`Aelf-Wait city, sinking slowly in time.`,
`Archaean adventurers, statue-slow.`,
`Time's mandala, its never-ceasing monks.`,
`Morlocks with night-lamps and eye-seeking darts.`,
`The fortress climb of Uncle Spine, well hid.`,
`City of the Opaque Eye, ruled by Doom.`,
`Olm on an epic migration rappel.`,
`Prison of the Daemon Choir, feared by all.`,
`Death dervish suicide squad, ride spiders.`,
`Subducted rocket silo of ancient make.`,
`Dugout towns, built in old workings of war.`,
`Bat-Riders, taking the tunnels at speed.`,
`Sacristy of Gloom, cloaked in sombre light.`,
`A Speleo-Mage and her seven thieves.`,
`Tumour-Mound of the Termites Chaotic.`,
`Mirror-Ville, accessed through volcanic glass.`,
`Stew-merchants carting their cauldron of slops.`,
`The Energy Saint's electrical prayers.`,
`Frantic Cambrimen looking for a fight.`,
`Shifting conch-cave of the stone-smuggling thieves.`,
`Hell-Town, kept by Cop Daemons bound in pairs.`,
`Sleepy mage, cradled in her golem's arms.`,
`Touch-Cut braille stone of the blind creator.`,
`A wall-crawling cannibal's quiet crusade.`,
`Cavern-plain of endlessly shifting stone.`,
`Fishing village hidden under the cliffs.`,
`Crime Bird rules a wandering orphan tribe.`,
`The Lama-Troll, regenerating dreams.`,
`Lamenters and lunatice migrating.`,
`Cave of Neutrality (not much goes on).`,
`Cold Volcano market of slaves and souls.`,
`Library of slaves, each memorised books.`,
`Lone child whose guard is the border of night.`,
`Muttering voices ghost to you through the walls.`,
`Gold-guarding golems confused by a rhyme.`,
`A silver thread leads through the shadow gate.`,
`Alric the organist pipes in his tomb.`,
`Riddle-Twist caverns are half-drowned, but safe.`,
`Murdered clones of you, naked, stripped and torn.`,
`Hoarders of the mist-mould, under attack.`,
`The Fear-King flees and begs for vengeful swords.`,
`Mobius-Fort of the Queen that wove time?`,
`The Arsenic road will get you there, half-dead.`,
`The darkness here cups lamps and puts them out.`,
`Murdered map-merchant, his secrets un-found.`,
`The wing of a dead moth reveals a plot.`,
`Undead thieves guard the Twisted God's crown vault.`,
`Dive the vertical Archipelago.`,
`Walls scarred by something trying to get away.`,
`Thastrovect, the risk-mad gambling Lich.`,
`The ghoul-priest gasps his final secret out.`,
`This maze hides Life-Knights, honourable undead.`,
`Black-Smoker climb leads to Sulphurous wealth.`,
`An evil Lord that hails you with your crimes.`,
`Robuskinot, the fence of stolen spells.`,
`The waterfall hides secret city gates.`,
`The Palace of Sighs is ruled by a ghost.`,
`Insanity Crawl cannot be climbed sane.`,
`Escaped slaves scream at the sight of you, and flee.`,
`Deep Janeen drifting on his carpet of gold.`,
`Hot girls in danger from a secret foe.`,
`The Maze-Monkey made his own, and hides still.`,
`This sinkhole takes you past Hell, but it's fast.`,
`Sorcerer's Delve with beings of horrid light.`,
`Fleeing thief, highly skilled, nearly dead, but rich.`,
`The mine-monk holds heretic hordes at bay.`,
`Port-Vertical is empty now, and still.`,
`The silk-bridge spiders charge a fleshy toll.`,
`The Psy-Lord's Mind-Mines; cyclic escapees.`,
`Devils-Financial, disguised as things meek.`,
`The merchant's guards are dead, the bandits too.`,
`The Sons of the Consuming One wait here.`,
`White-Diamond river hides silent stone isles.`,
`The flesh-rift and its delicate consent.`,
`Seller of swords, broken, brittle, and bejewelled.`,
`Dragon seeks recruits, interviews in dreams.`,
`This truth-obsessed Aelf broods still in her Hall.`,
`A Frost-Giant ferry wades the fire, for gold.`,
`Signs of your passage where never you were.`,
`Phat-stacked abandoned aristocrat cats.`,
`Abduct a princess, fat reward, you in?`,
`The mage's labours hid a mighty Delve.`,
`Gigaplex Rapids needs pilots with Math.`,

];

document.getElementById("encounterplace333").innerHTML = ``+encounter333[r(100)]+``;

}


function searchveins333(){


var search333 = [

`Climbing Harness (-fall damage, +abseiling)`,
`Climbing Harness (-fall damage, +abseiling)`,
`Climbing Harness (-fall damage, +abseiling)`,
``+String(r(4)+r(4))+` Functional Dvargir Carabiners (+clip on and off ropes)`,
``+String(r(4)+r(4))+` Functional Dvargir Carabiners (+clip on and off ropes)`,
`A fuel brick (1 hour of flame)`,
`A fuel brick (1 hour of flame)`,
`Dynamic Spidersilk rope. (-50hp fall damage, once)`,
`Dynamic Spidersilk rope. (-50hp fall damage, once)`,
`A climbing pick. (+climbing, weapon)`,
`A climbing pick. (+climbing, weapon)`,
`A clock-bow. (auto-loads, must be wound between battles, explodes on fumble)`,
`A clock-bow. (auto-loads, must be wound between battles, explodes on fumble)`,
`A lamp. (see lamps)`,
`A lamp. (see lamps)`,
`A lamp. (see lamps)`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
``+String(r(10)+r(10)+r(10)+r(10))+` lumes.`,
`'Miner's Friend'. (canary, detects toxic vapors, then dies)`,
`Psihemoth Memory Key. (open your own head for 1d6 damage, then traverse your memories)`,
`Looserope, 50'. (unties itelf on a command word)`,
`Insane dErO diary. (describes how to destroy mind machine, but machine works on you more the closer you are)`,
`Neolithic man-shape in clay. (takes damage instead of holder. If it breaks, take all damage at once)`,
`Dart that works once. (casts flesh-to-chrome)`,
`Wedding ring. (psionic link to unknown person who asks what happened to their husband/wife)`,
`Can of Dvargir spray-paint.`,
``+String(r(6))+` Demonic Pacts. Body was of an extremely evil named villain. Gain `+String(r(20))+`x experience and title "slayer of ____" where ____ is the body you looted this from. `+String(r(6))+` demons appear in order of strength.`,
`Body has a list of names tattooed on it. All are crossed out except for two. Penultimate name is yours, last name is of (a notable enemy npc).`,
`Grapple Spider. (iron grapple, clings like spider when thrown, must be fed blood)`,
`Vampire court subpoena for random NPC.`,
`An unassigned slavehunter's license, warrant, and badge.`,
`Instructions and countersigns for a secret rendezvous with a race totally opposed to the holder.`,
`Shifting Archaean dagger that causes blood to rust. (+1d10 vs foes with red blood, if it touches metal, both it and metal rust to nothing)`,
`A myco-lucent necklace with `+String(r(6)+r(6))+` jewels that produce spore effects when crushed.`,
``+String(r(6))+` Yoon-Suin Smokerope cigarettes. (smoke drifts up,adheres, then becomes rope)`,
`Book of Acid. (look inside, become woozy, vomit up acid)`,
`Pulsar Stone. (hand sized crystal, looking through lets you see distant pulsars)`,
`Set of silver blades for flensing precisely the skin of the human face.`,
`Baby brain in bottled brine. (neurovore bugging and communication technology)`,
``+String(r(4))+` vials of Heroin with Aelf-Adal syringes.`,
``+String(r(4))+` Funginid Mind-Spores (thumb sizes, fractal, soft, casts Speak With Mushrooms when consumed)`,
`Dvargir mushroom vodka. (+save vs magic, WIS test to stop arguing, failure=amount of people you must persuade in order to stop)`,
`dErO Conspiracy Pills. (character can hear players and refereee talking, must not let them know!)`,
`Pair of dice.`,
`Loaded pair of dice.`,
`Small, starved Gnonmen, gagged and tied up.`,
`A razor, mirror, and soap.`,
`Angleable steel mirror on extendible 6-foot brass pole.`,
`Olm-carved slender short-sword carved entirely from bone.`,
`Chunky brass cylindrical finger ring. (silent, reliable clock that pricks finger every hour)`,
`50 foot of nightengale chain. (slender, light as rope, sings softly under pressure)`,
`Spoolable fishing line with elegant chemiluminescent lures.`,
`Elegant Meerschaum miner's pipe with lid. Holds tiny fire spirit, never goes out. Can only light small things.`,
`Aelf-Adal ring. (wearer vomits spiders that surround them, if wearer isn't afraid, they can spider climb)`,
`Aelf-Adal Arak. Drink must be allowed to settle. (top layer=+insight but curse. bottom layer removes curse, instantly makes drunk, wipes `+String(r(6)+r(6))+` hours from memory)`,
`Aelf-Adal manacles. Syringe-thin inter-penetrating bars, driven through forearms like hair pins. Linked by slender chains.`,
``+String(r(6))+` Dvargir manacles. Plastic zip-ties.`,
`Aelf-Adal climbing harness. (looks cool, slim fit)`,
`Cloaksmoke. Pungent incense. (forces stealthy/shapechanging predators to immediately attack)`,
`Geophone. Delicate Dvargir make. (can hear sounds through 200 feet of stone)`,
`The genes of a Cambriman. Like helix of tiny wet pearls. Unstable.`,
`An occultum coin.`,

];

document.getElementById("searchplace333").innerHTML = ``+search333[r(100)]+``;

}


function veinsname333(){


var name1333 = [

`Latipan`,
`Laghu`,
`Kua Kua`,
`Krabi`,
`Koumac`,
`Kolokafa`,
`Kizilelma`,
`Kilsi`,
`Kembus`,
`Kef`,
`Kazumura`,
`Kavakuna`,
`Kanca`,
`Kamamba`,
`Jaskina`,
`Ile`,
`Hugo`,
`Hotat`,
`Heiowa`,
`Harasib`,
`Guixani`,
`Grotta`,
`Groot`,
`Great`,
`Grange`,
`Grand`,
`Gokgul`,
`Glamoko`,
`Ghor`,
`Ghaub`,
`Ghar`,
`Gamvra`,
`Gamsoui`,
`Furnia`,
`Dunekdib`,
`Eyrif`,
`Eyle`,
`Esprit`,
`Esher`,
`Namgamdok-gul`,
`Yeongweol-gun`,
`Echo`,
`Ease`,
`Complego`,
`Columbine`,
`Cap Corse`,
`Callao`,
`Bzybsky`,
`Busla`,
`Boljenac`,
`Bim`,
`Beysehir`,
`Beke`,
`Baradla`,
`Badict`,
`Aven`,
`Acho`,
`Luwang`,
`Mavro`,
`Mbao`,
`Mogote`,
`Montagne`,
`Monte`,
`Nita`,
`Ojo`,
`Voragine`,
`Patale`,
`Uchimagi`,
`Astraka`,
`Poloska`,
`Pozzo`,
`Rangetko`,
`Prot`,
`Rakou`,
`Raspora`,
`Reseau`,
`Rey`,
`Salmon`,
`Salzburger`,
`Schachta`,
`Selminum`,
`Shabun`,
`Lough`,
`McClung`,
`Malham`,
`Sof`,
`Stary`,
`Sumidero`,
`Tawi`,
`Terbil`,
`Abisso`,
`Theodor`,
`Tingo`,
`Torca`,
`Tuzo`,
`Tzani`,
`Uli`,
`Wind`,
`Wit`,
`Atishalla`,

];


var name2333 = [

`Comici`,
`Fonda`,
`Fulmini`,
`Monte Bul`,
`Tunkul`,
`Xpukil`,
`Do`,
`Jahn`,
`Gupha`,
`Pot`,
`Oke ke`,
`Sham`,
`Barlang`,
`Sejourne`,
`Cueva`,
`Khrebet`,
`Gill`,
`Carrowmere`,
`Crawl`,
`Chorreadero`,
`Uzueka`,
`Ghyll`,
`Gargano`,
`Volanti`,
`Oct`,
`Martel`,
`Suess`,
`Pezenas`,
`Creek`,
`Dara`,
`Fitton`,
`Glauici`,
`Dalan`,
`Hassan`,
`Karker`,
`Zaghouan`,
`Slocker`,
`Zab`,
`Fontein`,
`Gugliemo`,
`Guinjau`,
`Gupha`,
`Heia`,
`Pandoring`,
`Bandzioch`,
`Sniezna`,
`Ridge`,
`Jama`,
`Proval`,
`Tikharbai`,
`Harbatik`,
`Ponor`,
`Jeskyne`,
`Oros`,
`Corrib`,
`Dunya`,
`Ori`,
`Grubug`,
`Skiadi`,
`Hul`,
`Karst`,
`Noir`,
`Malo`,
`Nanta`,
`Guarena`,
`Tchuka`,
`Chhango`,
`Toplanita`,
`Vintului`,
`Jama`,
`Blanco`,
`Mandini`,
`Pot`,
`Skocjan`,
`Maja`,
`Ded`,
`Cintolo`,
`Rose`,
`Schacht`,
`Towiani`,
`Tem`,
`Kale`,
`Aonda`,
`Menor`,
`Sabana`,
`Omar`,
`Hrad`,
`Yochib`,
`Atair`,
`Tem`,
`Ruesie`,
`Brosen`,
`Maria`,
`Jou`,
`Wilson`,
`Spilios`,
`Guria`,
`Rift`,
`Tamdoun`,
`Nis`,

];

var namefull333 = [

``+name1333[r(100)]+` `+name2333[r(100)]+``

];

document.getElementById("nameplace333").innerHTML = ``+namefull333[r(1)]+``;

}


function veinsnoblename333(){


var noblename1333 = [

`Sotsbarkgrotten`,
`Vatnajokull`,
`Veshtoroc`,
`Bodabrottorna`,
`Chichicasapan`,
`Dongryong-gul`,
`Golondrinas`,
`Kanchanaburi`,
`Karangbolong`,
`Kolkblaser`,
`Konepruske`,
`Pollaraftra`,
`Pollnagollum`,
`Rushmangat`,
`Soldatskaya`,
`Thabazimbi`,
`Soifjorden`,
`Chandang-gul`,
`Caroajoapan`,
`Majilis`,
`Abisimo`,
`Balangangan`,
`Foglepole`,
`Niigata`,
`Resumidero`,
`Santoanos`,
`Sima`,
`Sumidero`,
`Torca`,
`Tunel`,
`Uanh`,
`Gorgoroth`,
`Gragareth`,
`Isgrotten`,
`Jashchick`,
`Nidlenloch`,
`Pinargozu`,
`Pollnacrom`,
`Zolushika`,
`Zsomboly`,
`Yolhafiri`,
`Gharkniz`,
`Skocjanske`,
`Guptesway`,
`Hooloch`,
`Dudenuik`,
`Ferenec`,
`Alexander`,
`Aggtelek`,
`Maxwelton`,

];


var noblename2333 = [

`Don`,
`Doom`,
`Et`,
`Von`,
`Te`,
`Von-Der`,
`Of`,
`Des`,
`Bone`,
`Da`,
`Mock`,
`Echt`,
`Yr`,
`Bok`,
`El`,
`De`,
`Spel`,
`Cut`,
`Des`,
`By`,
`Org`,
`Le`,
`Al`,
`Ken`,
`Th'`,
`Art`,
`Fault`,
`Is`,
`Hect`,
`Ig`,
`Cry`,
`Pseu`,
`Ten`,
`Eon`,
`Op`,
`Hy`,
`Grot`,
`Com`,
`Ot`,
`Ken`,
`Cut`,
`An`,
`Von-der`,
`Cone`,
`Drone`,
`Myco`,
`Nyco`,
`Psy`,
`Gul`,
`Hurt`,

];


var noblename3333 = [

`Juvenal`,
`Kaua`,
`Tseb`,
`Humbolt`,
`Pahu`,
`Linth`,
`Laraboro`,
`Tenebres`,
`Norman`,
`Diamante`,
`Huagapo`,
`Uchkupisjo`,
`Ogof`,
`Pipe`,
`Goranan`,
`Juxtlahuaca`,
`Precipico`,
`Aire`,
`Pins`,
`Frosen`,
`Nita`,
`Pot`,
`Jinn`,
`Karst`,
`Toxin`,
`Nogal`,
`Milpo`,
`Atikpak`,
`Jornas`,
`Sumidors`,
`Claonite`,
`Kananda`,
`Discoschacht`,
`Monsterhole`,
`Urrielto`,
`Ahuihuitzrapa`,
`Ambatoharanana`,
`Kulogorskaya`,
`Mangawhitikau`,
`Antsatrabonko`,
`Schwyzerschacht`,
`Siebenhengste`,
`Rouagrottorna`,
`Angurtidorgius`,
`Jordbrungrotten`,
`Kappasjokkgrotten`,
`Huehuetenango`,
`Kel'Ketchkhen`,
`Simmons-Mingo-Mg`,
`Kamenitim`,

];

var noblenamefull333 = [

``+noblename1333[r(50)]+` `+noblename2333[r(50)]+` `+noblename3333[r(50)]+``

];

document.getElementById("noblenameplace333").innerHTML = ``+noblenamefull333[r(1)]+``;

}


function veinseffects333(){


var effects333 = [

`Paranoia. You know that a fellow PC is hiding something from you. Experience points freeze until you force them to reveal it.`,
`Paranoia. You know that a fellow PC is hiding something from you. Experience points freeze until you force them to reveal it.`,
`Paranoia. You know that a fellow PC is hiding something from you. Experience points freeze until you force them to reveal it.`,
`Paranoia. You know that a fellow PC is hiding something from you. Experience points freeze until you force them to reveal it.`,
`Paranoia. You know that a fellow PC is hiding something from you. Experience points freeze until you force them to reveal it.`,
`Rage. You can no longer control your resentment and suspicion. Experience points freeze until you physically and directly harm a teammate. Until you comm9it this action, the Referee may force it upon you on the failure of any roll.`,
`Rage. You can no longer control your resentment and suspicion. Experience points freeze until you physically and directly harm a teammate. Until you comm9it this action, the Referee may force it upon you on the failure of any roll.`,
`Rage. You can no longer control your resentment and suspicion. Experience points freeze until you physically and directly harm a teammate. Until you comm9it this action, the Referee may force it upon you on the failure of any roll.`,
`Rage. You can no longer control your resentment and suspicion. Experience points freeze until you physically and directly harm a teammate. Until you comm9it this action, the Referee may force it upon you on the failure of any roll.`,
`Rage. You can no longer control your resentment and suspicion. Experience points freeze until you physically and directly harm a teammate. Until you comm9it this action, the Referee may force it upon you on the failure of any roll.`,
`Weight obsession. You must find a way to reduce your load. Throw something away or drastically alter its form to reduce its weight.`,
`Weight obsession. You must find a way to reduce your load. Throw something away or drastically alter its form to reduce its weight.`,
`Weight obsession. You must find a way to reduce your load. Throw something away or drastically alter its form to reduce its weight.`,
`You now lie half-awake and hallucinate instead of dreaming. Name your most common vision. If rolled twice you can create this vision in darkness, casting it as an illusion spell by having a brief conversation with the target. If thrice, the vision will appear in your 'waking' hours and call you. If four times, you must obey.`,
`You now lie half-awake and hallucinate instead of dreaming. Name your most common vision. If rolled twice you can create this vision in darkness, casting it as an illusion spell by having a brief conversation with the target. If thrice, the vision will appear in your 'waking' hours and call you. If four times, you must obey.`,
`You now lie half-awake and hallucinate instead of dreaming. Name your most common vision. If rolled twice you can create this vision in darkness, casting it as an illusion spell by having a brief conversation with the target. If thrice, the vision will appear in your 'waking' hours and call you. If four times, you must obey.`,
`If you wake up in darkness, you remember exactly where you went to sleep, the precise dimensions of the enclosing space, and the exact location of every nearby object. You will not need to fumble for your sword or search to locate an exit you have seen.`,
`If you wake up in darkness, you remember exactly where you went to sleep, the precise dimensions of the enclosing space, and the exact location of every nearby object. You will not need to fumble for your sword or search to locate an exit you have seen.`,
`Any sense of claustrophobia is gone. You do not fear any enclosed space, no matter how long you are there... in fact, you prefer it. Your memory of the sun is gone. You may not refer to it or describe it.`,
`Any sense of claustrophobia is gone. You do not fear any enclosed space, no matter how long you are there... in fact, you prefer it. Your memory of the sun is gone. You may not refer to it or describe it.`,
`You can identify blood by taste. The species and, if you have tasted it before, the individual. Roll twice and you must identify any blood by taste.`,
`Your pupils are permanently dilated to their maximum extent. Add 30' to the distance you can see. You are easily blinded.`,
`Each time you roll this, go down to the next lightest skin pigmentation. The last three are Caucasion, Albino, Translucent.`,
`Each time you roll this, go down to the next lightest skin pigmentation. The last three are Caucasion, Albino, Translucent.`,
`Each time you roll this, go down to the next lightest skin pigmentation. The last three are Caucasion, Albino, Translucent.`,
`Your immune system has collapsed. You have no save versus disease. You must trade with the Funginids for a symbiotic fungal replacement.`,
`Lose the hair from your body, or your head.`,
`Lose the hair from your body, or your head.`,
`Hyper-sensitive skin. You no longer wear clothes. With naked skin you can sense the movement of air around you. 50% naked you can sense the size of a cave around you. 90%, the size of the local system. 100% and you can sense local movement, the rough size and speed of things moving in the cave.`,
`Hyper-sensitive skin. You no longer wear clothes. With naked skin you can sense the movement of air around you. 50% naked you can sense the size of a cave around you. 90%, the size of the local system. 100% and you can sense local movement, the rough size and speed of things moving in the cave.`,
`Subconscious sonar. You compulsively click your tongue to discover the distance of nearby surfaces. You can scan for solid objects within 50'. It is hard for you to stop doing this.`,
`Subconscious sonar. You compulsively click your tongue to discover the distance of nearby surfaces. You can scan for solid objects within 50'. It is hard for you to stop doing this.`,
`You hunger for silence. The rhythm of your conversations slows imperceptibly. You breathe out single words. Shouting becomes intolerable, even in times of danger. You must pass a Wisdom test to raise your voice.`,
`You hunger for silence. The rhythm of your conversations slows imperceptibly. You breathe out single words. Shouting becomes intolerable, even in times of danger. You must pass a Wisdom test to raise your voice.`,
`Osteocytes. You begin to develop frills and ridges of bone on your skull. These extend through the skin. They may be horns, ridges, spikes, or something else. The more you roll this result the more elaborate they become.`,
`Osteocytes. You begin to develop frills and ridges of bone on your skull. These extend through the skin. They may be horns, ridges, spikes, or something else. The more you roll this result the more elaborate they become.`,
`Your finger bones lengthen and crook permanently. This provides a tireless hold while climbing, so you can hang on for a long as you need to. You have difficulty doing fine work.`,
`Your finger bones lengthen and crook permanently. This provides a tireless hold while climbing, so you can hang on for a long as you need to. You have difficulty doing fine work.`,
`Your time sense erodes without any realisation; your wake-sleep cycle extends from 24 hours to 48 if rolled twice, then to 72. You do not notice this.`,
`Your time sense erodes without any realisation; your wake-sleep cycle extends from 24 hours to 48 if rolled twice, then to 72. You do not notice this.`,
`Your time sense erodes without any realisation; your wake-sleep cycle extends from 24 hours to 48 if rolled twice, then to 72. You do not notice this.`,
`Respiration and digestion slow when still. If doing nothing you can go 30 seconds between breaths. You barely need food if all you do is wait.`,
`Respiration and digestion slow when still. If doing nothing you can go 30 seconds between breaths. You barely need food if all you do is wait.`,
`Your breathing becomes silent. If you were next to someone, they would feel your breath on their face before hearing it.`,
`Your breathing becomes silent. If you were next to someone, they would feel your breath on their face before hearing it.`,
`You no longer trust paper as it decays too fast. You start to tattoo your knowledge and maps onto your skin. Your self-developed code is shorter than writing and means your flayed skin would be useless as a map for others. A clever trick, you think. You start with your forearms and thighs then spiral out.`,
`You no longer trust paper as it decays too fast. You start to tattoo your knowledge and maps onto your skin. Your self-developed code is shorter than writing and means your flayed skin would be useless as a map for others. A clever trick, you think. You start with your forearms and thighs then spiral out.`,
`You can taste lies on someone's breath as they speak. You must be within kissing distance.`,
`You can taste lies on someone's breath as they speak. You must be within kissing distance.`,
`You compulsively sharpen your teeth.`,
`You compulsively sharpen your teeth.`,
`There is a darkness in your belly. When you scream, deliberately or not, a minor Darkness spell is cast from your mouth for the duration of the scream.`,
`There is a darkness in your belly. When you scream, deliberately or not, a minor Darkness spell is cast from your mouth for the duration of the scream.`,
`You must name any flame that you light. You must speak to them as if they were people. They take up a retainer space. They have morale. They may keep watch for you. They may also betray you.`,
`You must name any flame that you light. You must speak to them as if they were people. They take up a retainer space. They have morale. They may keep watch for you. They may also betray you.`,
`Scent identity is now more real to you than visual identity. If separated from your friends, you will not fully recognise them till you smell them all over.`,
`Scent identity is now more real to you than visual identity. If separated from your friends, you will not fully recognise them till you smell them all over.`,
`You no longer recognise your own racial nature. You regard yourself as "other". You gain no bonuses when communicating with your own race.`,
`You no longer recognise your own racial nature. You regard yourself as "other". You gain no bonuses when communicating with your own race.`,
`You must make a Wisdom test to avoid compulsive consumption of your fallen foes if they are of animal intelligence; if rolled twice, named beings; if thrice, even your own species.`,
`You must make a Wisdom test to avoid compulsive consumption of your fallen foes if they are of animal intelligence; if rolled twice, named beings; if thrice, even your own species.`,
`You must make a Wisdom test to avoid compulsive consumption of your fallen foes if they are of animal intelligence; if rolled twice, named beings; if thrice, even your own species.`,
`You must make a Wisdom test to avoid compulsive consumption of your fallen foes if they are of animal intelligence; if rolled twice, named beings; if thrice, even your own species.`,
`Your eyelids become translucent; you are hard to surprise if sleeping but are easy to blind.`,
`Your limbs and torso grow subtly longer yet retain the same mass. At first gangly (10%); if rolled twice, freakish (20%); if thrice, trollish (30%) and you go up a size category.`,
`Your limbs and torso grow subtly longer yet retain the same mass. At first gangly (10%); if rolled twice, freakish (20%); if thrice, trollish (30%) and you go up a size category.`,
`Your limbs and torso grow subtly longer yet retain the same mass. At first gangly (10%); if rolled twice, freakish (20%); if thrice, trollish (30%) and you go up a size category.`,
`Your vision spectrum drops into a deeper shade of red. You gain thermal vision but blue is now simply black to you. If you had thermal vision you can now see vague x-ray glows.`,
`Mask-hunger. You become obsessed with protecting your image. Make a mask and wear it continually.`,
`WHen you are not exerting yourself, your body temperature drops to the ambient temperature of the environment. You cannot die from hypothermia. Neither can you warm others who are suffering. You may seem dead when you sleep.`,
`Shadows are portals from which you can be watched. You cannot sleep or relax in shadow. You need complete darkness. You can often spot illusions by watching their shadows.`,
`In absolute silence, just on the edge of hearing, you can hear the darkness speaking with itself. You do not like this. Learning its language is harder than any human tongue. Its discussions may be beyond you.`,
`Reflections are enemy selves. You will avoid them if you can and never discuss important business in front of them.`,
`Rapid protein conversion. You can gorge on meat to add 1 Strength per Hit Die consumed. So all of a 1 Hit Die creature, half a 2 dice creature, one tenth of a 10 hit dice creature, etc. The bonus lasts until you sleep.`,
`Always hungry. -1 Charisma unless just eaten. Can smell food on people if it is hidden.`,
`Your nails thicken and extend, becoming 1d3 weapons. If rolled twice, 1d4 weapons. If thrice, 1d6 weapons and are now claws... you will have difficulty with fine work.`,
`Your nails thicken and extend, becoming 1d3 weapons. If rolled twice, 1d4 weapons. If thrice, 1d6 weapons and are now claws... you will have difficulty with fine work.`,
`Your nails thicken and extend, becoming 1d3 weapons. If rolled twice, 1d4 weapons. If thrice, 1d6 weapons and are now claws... you will have difficulty with fine work.`,
`You must name any ropes you own and speak to them as if they were people. They take up a retainer spot. They have a morale. You can command them to unknot, they may inform you if they are damaged or not well secured, they may also betray you.`,
`You can and must use Speak With Air as a daily power.`,
`Bone collector. Every enemy you kill has one bone waiting for you, take it and wrap it carefully.`,
`Riddlemaster. You cannot refuse a riddle challenge. In appropriate circumstances you may riddle and gain bonuses to social situations.`,
`Psychic Scent. You can and must smell psionic influence. The smell is as slight as a cup of coffee but you will sense it if you get close enough.`,
`Magic Sense. Tip your head back, spread arms, close eyes, roll jaw and moan to detect magic. You will fell it in your teeth if it is within 50'.`,
`You gain a sense for the silent speech. If you see dwellers using it, you can get a good feel for the general tone and can spot simple words.`,
`Secrets. You hoard them. Must pass Wisdom test to willingly communicate any secret thing. For instance, the location of a secret door you just found, a letter you picked up, the last words of a foe.`,
`Cancer Totem. Build a totem of a Cancer Bear from bones and wear it continually. You believe this will protect you. It will. Once per level, in life threatening circumstances, it will act with the powers of a normal Calcinated Cancer Bear under your control.`,
`Face blind. You can't remember faces till you stroke them.`,
`Face blind. You can't remember faces till you stroke them.`,
`Tectonic dreams. Just before you fall asleep you can hear the murmuring of Substratals. You gradually learn that language and can speak it by the time you next level up.`,
`Tectonic dreams. Just before you fall asleep you can hear the murmuring of Substratals. You gradually learn that language and can speak it by the time you next level up.`,
`Ghost warden. You fear the spirits of those you have killed. Build, or obtain, an amulet to imprison them. Record them all. If it breaks, or is lost, they may get free (5% chance true per ghost).`,
`Magnetic sense. Iron in the rock will stop you reliably sensing North, but it can aid you in navigation nonetheless. Especially if blinded. Worked metal is like a burning torch to you. It can blind you if close enough. You don't like carrying metal weapons.`,
`Blood change. Your blood becomes an odourless, tasteless clear gel. It is hard to track you. If your skin is already translucent then your bones are almost visible through the cloudy flesh.`,
`Blood change. Your blood becomes an odourless, tasteless clear gel. It is hard to track you. If your skin is already translucent then your bones are almost visible through the cloudy flesh.`,
`Poison absorber. Poison still affects you as normal, but if you survive it, your body will hang onto the dose. You can transmit it via biting.`,
`Poison absorber. Poison still affects you as normal, but if you survive it, your body will hang onto the dose. You can transmit it via biting.`,
`Water sense. You can taste emissions from upstream in moving water. Anything pissing or bleeding within half a mile upstream.`,
`Water sense. You can taste emissions from upstream in moving water. Anything pissing or bleeding within half a mile upstream.`,
`You lose all desire to return to the surface. You belong here now.`,

];

document.getElementById("effectsplace333").innerHTML = ``+effects333[r(100)]+``;333

}